# SPDX-License-Identifier: BSD-2-Clause
# Copyright(c) HCL TECHNOLOGIES LTD
# Submitted on behalf of a third-party: Intel Corporation, a
# Delaware corporation, having its principal place of business
# at 2200 Mission College Boulevard,
# Santa Clara, California 95052, USA

import platform

Import('VRouterEnv')
Import('dpdk_lib')
env = VRouterEnv.Clone()

if not GetOption('without-dpdk') and 'enableN3K' in env['ADD_OPTS']:
    env.SConscript(
        'dpdk/n3k/SConscript',
        exports = ['VRouterEnv', 'dpdk_lib'],
        duplicate = 0
    )
