# SPDX-License-Identifier: BSD-2-Clause
# Copyright(c) HCL TECHNOLOGIES LTD
# Submitted on behalf of a third-party: Intel Corporation, a
# Delaware corporation, having its principal place of business
# at 2200 Mission College Boulevard,
# Santa Clara, California 95052, USA
#

Import('VRouterEnv')
Import('dpdk_lib')

env = VRouterEnv.Clone()

env.SConscript(
    'unit/SConscript',
    exports = ['VRouterEnv', 'dpdk_lib'],
    duplicate = 0
)

env.SConscript(
    'integration/SConscript',
    exports = ['VRouterEnv', 'dpdk_lib'],
    duplicate = 0
)

DPDK_TARGET = env['DPDK_TARGET']
build_dir = Dir(env['TOP']).abspath
dpdk_build_dir = '{}/vrouter/dpdk/{}'.format(build_dir, DPDK_TARGET)
dpdk_n3k_ut_app =  '{}/app/n3k-ut'.format(dpdk_build_dir)
exec_ut = env.Command("dpdk-n3k-ut", [], dpdk_n3k_ut_app)
env.Requires(exec_ut, dpdk_lib)
env.Alias("dpdk-n3k-ut", exec_ut)
