# SPDX-License-Identifier: BSD-2-Clause
# Copyright(c) HCL TECHNOLOGIES LTD
# Submitted on behalf of a third-party: Intel Corporation, a
# Delaware corporation, having its principal place of business
# at 2200 Mission College Boulevard,
# Santa Clara, California 95052, USA
#

Import('VRouterEnv')
Import('dpdk_lib')

env = VRouterEnv.Clone()

env.SConscript(
    'unit/SConscript',
    exports = ['VRouterEnv', 'dpdk_lib'],
    duplicate = 0
)

env.SConscript(
    'integration/SConscript',
    exports = ['VRouterEnv', 'dpdk_lib'],
    duplicate = 0
)
